//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdData
    {
        public int roll { get; set; }
        public string studentName { get; set; }
        public Nullable<int> standard { get; set; }
        public string gender { get; set; }
    }
}
